
server:
  port: 8183

spring:
  application:
    name: user-service
#These configuration is used to handle the data base connectivity with user name and password.(refer Hikari properties too.)
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/test_project_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30

Eureka:
#The flags set to true in order to register the user-service in eureka server as a micro service.
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instance:
      hostname: localhost
